// lib/lsa-states.ts
export const LsaState = {
  NAV_LEARN: "NAV_LEARN",
  NAV_CHALLENGE: "NAV_CHALLENGE",
  NAV_BADGES: "NAV_BADGES",
  NAV_LEADERBOARD: "NAV_LEADERBOARD",
  LEARN_VOCAB_SET: "LEARN_VOCAB_SET",
  LEARN_SNAKE_GAME: "LEARN_SNAKE_GAME",
  LEARN_GRAMMAR_EXPLAIN: "LEARN_GRAMMAR_EXPLAIN",
  LEARN_TETRIS_GAME: "LEARN_TETRIS_GAME",
  CHALLENGE_START: "CHALLENGE_START",
  CHALLENGE_FINISH: "CHALLENGE_FINISH",
} as const;

// (可選) 如果其他地方需要把 LsaState 當作型別使用，加上這行：
export type LsaStateType = typeof LsaState[keyof typeof LsaState];