-- LearningQuest 共用 Supabase Schema（控制組與實驗組共用）
-- 文件日期：2026-07-17
-- 注意：正式資料庫若已存在資料，請先備份並逐段核對，不要直接刪表重建。

create extension if not exists pgcrypto;

-- ============================================================
-- 1. profiles：兩組共用
--    由 auth.users 一對一建立，progress 以 JSONB 儲存前端進度。
-- ============================================================
create table if not exists public.profiles (
  id uuid not null,
  updated_at timestamp with time zone null default now(),
  full_name text null,
  school text null,
  grade text null,
  progress jsonb not null default '{}'::jsonb,
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign key (id)
    references auth.users (id) on delete cascade
) tablespace pg_default;

alter table public.profiles
  add column if not exists updated_at timestamp with time zone null default now(),
  add column if not exists full_name text null,
  add column if not exists school text null,
  add column if not exists grade text null,
  add column if not exists progress jsonb not null default '{}'::jsonb;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 補建既有 auth.users 但缺少 profiles 的資料列
insert into public.profiles (id)
select u.id
from auth.users u
left join public.profiles p on p.id = u.id
where p.id is null
on conflict (id) do nothing;

-- ============================================================
-- 2. lsa_logs：兩組共用
-- ============================================================
create table if not exists public.lsa_logs (
  id uuid not null default gen_random_uuid(),
  user_id uuid null,
  full_name text null,
  session_id text not null,
  action_state text not null,
  context_data jsonb null default '{}'::jsonb,
  created_at timestamp with time zone null default now(),
  constraint lsa_logs_pkey primary key (id),
  constraint lsa_logs_user_id_fkey foreign key (user_id)
    references auth.users (id)
) tablespace pg_default;

create index if not exists lsa_logs_user_created_idx
  on public.lsa_logs (user_id, created_at);
create index if not exists lsa_logs_session_created_idx
  on public.lsa_logs (session_id, created_at);
create index if not exists lsa_logs_action_created_idx
  on public.lsa_logs (action_state, created_at);

-- 查詢單一學生紀錄（請替換 UUID）
-- select id, user_id, full_name, session_id, action_state, context_data, created_at
-- from public.lsa_logs
-- where user_id = '63b479d3-d21c-40ec-93ad-911588143040'
-- order by created_at asc;

-- ============================================================
-- 3. leaderboard：兩組共用
-- ============================================================
create table if not exists public.leaderboard (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  full_name text null,
  game text not null,
  score integer not null,
  created_at timestamp with time zone null default now(),
  constraint leaderboard_pkey primary key (id),
  constraint unique_user_game unique (user_id, game),
  constraint leaderboard_user_id_fkey foreign key (user_id)
    references auth.users (id) on delete cascade
) tablespace pg_default;

create index if not exists leaderboard_game_score_idx
  on public.leaderboard (game, score desc);

-- ============================================================
-- 4. badge_leaderboard_ranked：兩組共用 View
--    這是使用者提供的現行邏輯：金 5、銀 3、銅 1。
-- ============================================================
create or replace view public.badge_leaderboard_ranked
with (security_invoker = on)
as
with badge_rows as (
  select
    p.id,
    p.full_name,
    case
      when jsonb_typeof(b.value) = 'object'::text
       and coalesce(b.value ->> 'tier'::text, ''::text) ~ '^[0-9]+$'::text
      then (b.value ->> 'tier'::text)::integer
      else 0
    end as tier
  from public.profiles p
  left join lateral jsonb_each(
    coalesce(p.progress -> 'badges'::text, '{}'::jsonb)
  ) b(key, value) on true
), ranked as (
  select
    badge_rows.id,
    badge_rows.full_name,
    count(*) filter (where badge_rows.tier = 3)::integer as gold,
    count(*) filter (where badge_rows.tier = 2)::integer as silver,
    count(*) filter (where badge_rows.tier = 1)::integer as bronze,
    (
      count(*) filter (where badge_rows.tier = 3) * 5
      + count(*) filter (where badge_rows.tier = 2) * 3
      + count(*) filter (where badge_rows.tier = 1)
    )::integer as score
  from badge_rows
  group by badge_rows.id, badge_rows.full_name
)
select id, full_name, gold, silver, bronze, score
from ranked
where full_name is not null
  and btrim(full_name) <> ''::text
  and (gold + silver + bronze) > 0;

-- ============================================================
-- 5. RLS 參考政策
-- ============================================================
-- 重要：security_invoker = on 的 badge view 會套用 profiles 的 RLS。
-- 若 profiles 只能讀自己，獎章排行榜就只會看到自己；若開放讀全部，
-- 則使用者可能直接讀到他人的 progress。正式環境需在「隱私」與
-- 「全體排行榜」之間採用受控 RPC／摘要表等方案，請勿盲目套用。

alter table public.profiles enable row level security;
alter table public.leaderboard enable row level security;
alter table public.lsa_logs enable row level security;

-- profiles：個人資料基本政策（會造成 security_invoker badge view 只看自己）
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select to authenticated
  using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles for insert to authenticated
  with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- leaderboard：所有登入者可讀排行榜，只能寫自己的列
drop policy if exists "leaderboard_select_authenticated" on public.leaderboard;
create policy "leaderboard_select_authenticated"
  on public.leaderboard for select to authenticated
  using (true);

drop policy if exists "leaderboard_insert_own" on public.leaderboard;
create policy "leaderboard_insert_own"
  on public.leaderboard for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "leaderboard_update_own" on public.leaderboard;
create policy "leaderboard_update_own"
  on public.leaderboard for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- lsa_logs：學生只能新增自己的事件；研究者以 service role／後台查詢
drop policy if exists "lsa_logs_insert_own" on public.lsa_logs;
create policy "lsa_logs_insert_own"
  on public.lsa_logs for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "lsa_logs_select_own" on public.lsa_logs;
create policy "lsa_logs_select_own"
  on public.lsa_logs for select to authenticated
  using (auth.uid() = user_id);

-- View 權限（是否能看到全體仍取決於 profiles RLS）
grant select on public.badge_leaderboard_ranked to authenticated;
